//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyApiClient.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerSrcPayment
    {
        public string bill_identifier { get; set; }
        public Nullable<decimal> payment_amt { get; set; }
        public Nullable<int> bank_code { get; set; }
        public Nullable<int> ref_code { get; set; }
        public Nullable<int> chanel_type { get; set; }
        public int Pkid { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
    }
}
